AY2425S1-CS2103T-F10-1/tp

docs/AboutUs.md

Update about us with my own info
close #16

Update about us

---

docs/AboutUs.md

Add my own personal description
close #17

Add Jeremy's about us

---

docs/DeveloperGuide.md

Updated the user stories according to the 3 levels indicated in the document.
Closes #28

Update user stories in Developer Guide

---

docs/DeveloperGuide.md

Update the use cases for ClientHub in the DeveloperGuide.md file 
Close #30

Add use cases for ClientHub

---

docs/DeveloperGuide.md

Update glossary terms in DeveloperGuide.md
close #35

Update glossary terms in DeveloperGuide.md

---

docs/DeveloperGuide.md

Edit the use cases in the DeveloperGuide.md file to follow the correct format.
Close #33

Edit use case format for developer guide

---

docs/DeveloperGuide.md

Add new non-functional requirements under the product scope
close #34

Add Non-Functional Requirements in DeveloperGuide

---

src/main/java/seedu/address/model/description/Description.java

- Add Description Class for future use in Person field of code. 
- Not fully integrated into the code yet
close #44

Add Description Class

---

src/main/java/seedu/address/commons/core/LogsCenter.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/UserPrefs.java
src/main/java/seedu/address/model/clienttype/ClientType.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedClientType.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/PersonUtil.java
src/test/java/seedu/address/testutil/TypicalPersons.java

- Edited remaining variables that still used tag in the name to client type
- Edited variables and code which used addressbook name and replace it with clienthub
closes #55 
- Update user guide
- Update developer guide

Update tag to clientType

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/test/java/seedu/address/testutil/PersonUtil.java

Added whitespace in front of ClientType to ensure description is added properly.
Closes #70

Debug failed test cases

---

src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java

Update description test and also logic manager
test to make sure it works

Updated description test

---

docs/UserGuide.md

- Added find phone feature
- Updated Tag to Client Type
- Updated AddressBook to ClientHub
Add screenshots when app is working
Closes #72

Added Find Phone

---

docs/UserGuide.md

Update user guide for find name command

Update user guide for find name command

---

docs/UserGuide.md
src/main/java/seedu/address/logic/parser/FindAddressCommandParser.java
src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java
src/test/java/seedu/address/logic/commands/FindAddressCommandTest.java
src/test/java/seedu/address/logic/parser/ClientHubParserTest.java
src/test/java/seedu/address/logic/parser/FindAddressCommandParserTest.java
src/test/java/seedu/address/model/person/AddressContainsKeywordsPredicateTest.java

Change predicate logic for findAddress
close #93

Update FindAddress Command

---

docs/diagrams/ArchitectureSequenceDiagram.puml
docs/diagrams/BetterModelClassDiagram.puml
docs/diagrams/CommitActivityDiagram.puml
docs/diagrams/LogicClassDiagram.puml
docs/diagrams/ModelClassDiagram.puml
docs/diagrams/ParserClasses.puml
docs/diagrams/UndoRedoState0.puml
docs/diagrams/UndoRedoState1.puml
docs/diagrams/UndoRedoState2.puml
docs/diagrams/UndoRedoState3.puml
docs/diagrams/UndoRedoState4.puml
docs/diagrams/UndoRedoState5.puml
docs/diagrams/UndoSequenceDiagram-Model.puml
docs/diagrams/tracing/LogicSequenceDiagram.puml

Update UML diagram with the correct
function and class names
close #95

Update UML diagram

---

src/main/java/seedu/address/model/person/ClientTypeContainsKeywordsPredicate.java

* Change the FindClientType command to a AND search. 
* Add a condition to check if the keywords list is empty.
close #97

Update FindClientType command

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/FindNameCommand.java
src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
src/test/java/seedu/address/logic/commands/FindCommandTest.java
src/test/java/seedu/address/logic/commands/FindNameCommandTest.java
src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java

Update the fn command 
Delete the find command test case

Branch update fn command

---

docs/UserGuide.md

* Update the User guide for the find client type command. 
* Change the description to describe the new and refine AND search instead of OR.
close #105

Update UserGuide for FindClientType Command

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/CommandResult.java
src/main/java/seedu/address/logic/commands/ExitCommand.java
src/main/java/seedu/address/logic/commands/HelpCommand.java
src/main/java/seedu/address/logic/commands/ViewCommand.java
src/main/java/seedu/address/logic/parser/ClientHubParser.java
src/main/java/seedu/address/logic/parser/ViewCommandParser.java
src/main/java/seedu/address/model/person/exceptions/PersonNotFoundException.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/ViewPersonWindow.java
src/main/resources/view/ViewPersonWindow.fxml
src/test/java/seedu/address/logic/commands/CommandResultTest.java
src/test/java/seedu/address/logic/commands/ExitCommandTest.java
src/test/java/seedu/address/logic/commands/HelpCommandTest.java
src/test/java/seedu/address/logic/commands/ViewCommandTest.java
src/test/java/seedu/address/logic/parser/ClientHubParserTest.java
src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java

* Add the ViewCommand and the related class such as ViewCommandParser.
* Add a new field to CommandResult to include showView
* Add the ViewPersonWindow UI and integrated it into MainWindow
* Add more test cases especially for ViewCommandTest
* Test case when there is no inputs into the predicate
close #104

Add View Command

---

docs/UserGuide.md

Added the sort command into user guide to show how it can be used.
Updated the table at the end of user guide to include fn and fc.
Closes #121

Update user guide to include Sort Command

---

src/main/java/seedu/address/logic/commands/SortCommand.java
src/main/java/seedu/address/logic/parser/ClientHubParser.java
src/test/java/seedu/address/logic/parser/ClientHubParserTest.java

- Added short command for sort "s"
- Added to parser
Closes #125

Add short form to sort command

---

src/main/java/seedu/address/ui/MainWindow.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/MainWindow.fxml
src/main/resources/view/PersonListCard.fxml
src/main/resources/view/ViewPersonWindow.css
src/main/resources/view/ViewPersonWindow.fxml

* Edit the MainWindow and ViewPersonWindow UI
* Create a ViewPersonWindow CSS file
* Need to check if UI will break when description is long
close #117

Update UI for MainWindow and ViewPersonWindow

---

docs/DeveloperGuide.md
src/main/java/seedu/address/logic/commands/SortCommand.java
src/main/java/seedu/address/model/ModelManager.java

- Remove unnecessary System print lines
- Remove other usages
- Updated link for Model.java in developer guide
Closes #138

Clean up unnecessary lines of code

---

src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/model/person/Description.java
src/test/data/JsonClientHubStorageTest/invalidPersonClientHub.json
src/test/data/JsonSerializableClientHubTest/invalidPersonClientHub.json
src/test/data/JsonSerializableClientHubTest/typicalPersonsClientHub.json
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/person/DescriptionTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java

- Description can now be up to 500 characters
- ClientType is now compulsory
- Deleted AddCommandParser testcase for testing for optional field(clientType no longer optional)
- Updated Testcases to comply with new parameters
closes #145

Update description and clientType

---

src/main/java/seedu/address/ui/HelpWindow.java
src/main/resources/view/HelpWindow.css
src/main/resources/view/HelpWindow.fxml
src/main/resources/view/MainWindow.fxml

Added all commands to help window for easy reference
close #110

Branch update help

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/FindNameCommand.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/logic/parser/FindNameCommandParser.java
src/main/java/seedu/address/logic/parser/ViewCommandParser.java
src/main/java/seedu/address/model/person/Name.java
src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
src/test/java/seedu/address/logic/parser/FindNameCommandParserTest.java
src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
src/test/java/seedu/address/model/person/NameTest.java

Change the format of the name to include letter, space and parenthesis only
Add test cases for FindCommandParser and FIndNameCommandParser
close #152

Update Add, View, FindName and Find function

---

src/main/resources/view/HelpWindow.css
src/main/resources/view/HelpWindow.fxml

* Refine HelpWindow UI
* Added scrollpane
close #155

Refine HelpWindow UI

---

src/main/java/seedu/address/logic/commands/ViewCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/ViewCommandTest.java

* Add new testcases for View Command
* Use CommandExceptions to handle invalid inputs
* Improve readability
close #161, close #118

Refine ViewCommand 

---

src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
src/main/java/seedu/address/logic/commands/reminder/DeleteReminderCommand.java
src/main/java/seedu/address/logic/commands/reminder/EditReminderCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/reminder/AddReminderParser.java
src/main/java/seedu/address/logic/parser/reminder/DeleteReminderParser.java
src/main/java/seedu/address/logic/parser/reminder/EditReminderParser.java
src/main/java/seedu/address/model/reminder/Reminder.java
src/main/java/seedu/address/model/reminder/ReminderDescription.java

- Add AddReminderCommand, EditReminderCommand, DeleteReminderCommand
- Add AddReminderParser, EditReminderParser, DeleteReminderParser
- Add Reminder class, and Reminder description class
- Fully implement all of them
close #168

Update code with new reminder logic

---

src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/ReminderCard.java
src/main/java/seedu/address/ui/ReminderListPanel.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/MainWindow.fxml
src/main/resources/view/ReminderCard.fxml
src/main/resources/view/ReminderListPanel.fxml

* Create a container to display all the reminders of the user. 
* Currently, the UI is filled with dummy data.
close #175

Create a simple ReminderList UI

---

src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml
src/main/resources/view/ViewPersonWindow.fxml

* Add some padding between the JavaFX UI components within the Person card.
* Make the container holding the description big enough to hold the max character limit.
* Remove the description label in Personcard as it will be shown in ViewPerson.
close #177

Refine Personcard UI

---

src/main/java/seedu/address/logic/parser/FindClientTypeCommandParser.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java

* Add a string split to split the string into separate tokens in the form of a String array. 
For eg. Investment Plan will be split into ["Investment", "Plan"].
close #184

Fix the main Find Command for client types

---

src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java

* Add more testcases for ViewCommandParser for greater coverage.
close #163

Add more testcases in ViewCommandParserTest

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
src/main/java/seedu/address/model/reminder/Reminder.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/ReminderCard.java
src/main/java/seedu/address/ui/ReminderListPanel.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/ReminderCard.fxml

* Add getDisplayReminders method into the Logic interface. 
* The method was implement in LogicManager.
* Change the fieldname "person" to "personName" for better readibility.
* AddReminderCommand now creates a new Reminder taking in the fullname of
the person. This is so that we can show the fullname of the user on the
reminder list instead of the input name.
* Link Reminder logic to the UI
close #187

Link Reminder logic to UI

---

docs/UserGuide.md

* Fix typos that caused the image to not display correctly on GitHub
* Remove previous comments

Fix errors in UG

---

docs/UserGuide.md
src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
src/test/java/seedu/address/logic/LogicManagerTest.java

- Updated formatting of error messages
- Added more info like "use list command to check clients"
- Changed parser logic to no longer allow for non-Name inputs
close #195

Update Code to fix bug

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
src/main/java/seedu/address/logic/commands/reminder/DeleteReminderCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/model/ClientHub.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/UniquePersonList.java
src/main/java/seedu/address/model/reminder/Reminder.java
src/main/java/seedu/address/model/reminder/ReminderDescription.java
src/main/java/seedu/address/model/reminder/ReminderList.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/main/java/seedu/address/storage/JsonAdaptedReminder.java
src/main/java/seedu/address/storage/JsonSerializableClientHub.java

Update reminder so that it is an optional field of person
Update reminder so that the UI is capturing all add and delete immediately
close #211

Branch add reminder field

---

src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
src/main/java/seedu/address/model/reminder/Reminder.java

* When new reminder is add, the fullname will be shown instead of the input name.
close #212

Fix the add reminder command

---

src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
src/main/java/seedu/address/logic/commands/reminder/DeleteReminderCommand.java
src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
src/test/java/seedu/address/testutil/PersonBuilder.java

- Reminder Add and delete is working
close #214

Update Reminder code

---

src/main/java/seedu/address/model/util/SampleDataUtil.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/model/reminder/ReminderDescriptionTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java

* Bug fixes to some of the test cases
close #216

Branch fix testcases

---

src/main/java/seedu/address/model/ClientHub.java
src/main/java/seedu/address/storage/JsonSerializableClientHub.java
src/test/data/JsonClientHubStorageTest/invalidPersonClientHub.json
src/test/data/JsonSerializableClientHubTest/duplicatePersonClientHub.json
src/test/data/JsonSerializableClientHubTest/typicalPersonsClientHub.json
src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
src/test/java/seedu/address/logic/commands/reminder/DeleteReminderCommandTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java
src/test/java/seedu/address/testutil/TypicalReminders.java

Update Json files to have reminder fields

Update Json files

---

README.md
docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
src/test/java/seedu/address/logic/commands/reminder/DeleteReminderCommandTest.java
src/test/java/seedu/address/model/reminder/ReminderDescriptionTest.java
src/test/java/seedu/address/testutil/TypicalReminders.java

Update md files to delete the trailing whitespaces

Update md files for style

---

src/main/resources/view/MainWindow.fxml

* Add width to the reminderlistpanel.
close #222

Minor UI fix to ReminderList

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/PersonUtil.java
src/test/java/seedu/address/testutil/TypicalPersons.java

* Fix all related issues regarding the edit command tests.
* Temp fix to JsonSerializableClientHubTest
* Make it such that everytime getTypicalClientHub is called, a fresh copy of the data is created to ensure that all tests are working a "fresh" client hub.
* Need to relook at our implementation for `edit` method.
close #220

Fix EditCommand tests

---

src/test/java/seedu/address/logic/commands/DeleteCommandTest.java

Add testcase to test for error when deleting
person when they have reminder

Add new TestCase for deletecommand

---

src/main/java/seedu/address/ui/CommandBox.java

* Add command history feature into Command Box
* Users can now use the `UP` and `DOWN` keys to navigate the commands that they have entered previously.
close #237

Add Command History feature

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/FindAddressCommand.java
src/main/java/seedu/address/logic/commands/FindClientTypeCommand.java
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/FindNameCommand.java
src/main/java/seedu/address/logic/commands/FindPhoneCommand.java
src/main/java/seedu/address/logic/commands/SortCommand.java
src/test/java/seedu/address/logic/commands/FindAddressCommandTest.java
src/test/java/seedu/address/logic/commands/FindClientTypeCommandTest.java
src/test/java/seedu/address/logic/commands/FindCommandTest.java
src/test/java/seedu/address/logic/commands/FindNameCommandTest.java
src/test/java/seedu/address/logic/commands/FindPhoneCommandTest.java
src/test/java/seedu/address/logic/commands/SortCommandTest.java

- Changed listed view to show singularity if list has 0 or 1 person
- Changed persons to clients
Closes #209

Changed persons to clients and follow the plurality

---

src/main/java/seedu/address/logic/commands/FindCommand.java

* Reorganise the command output message find command.
close #208

Refine command output for FindCommand

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/model/clienttype/ClientType.java
src/main/java/seedu/address/model/person/Phone.java
src/test/data/JsonSerializableClientHubTest/typicalPersonsClientHub.json
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/person/ClientTypeContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/NameContainsKeywordsDeletePredicateTest.java
src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/PhoneTest.java
src/test/java/seedu/address/testutil/TypicalPersons.java

- Add phone restriction of 8 characters
- Add restriction on edit to not be able to clear client type
- Update tests
close #192

Edit command fix

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/ExitCommand.java
src/main/java/seedu/address/logic/commands/FindAddressCommand.java
src/main/java/seedu/address/logic/commands/FindClientTypeCommand.java
src/main/java/seedu/address/logic/commands/FindNameCommand.java
src/main/java/seedu/address/logic/commands/FindPhoneCommand.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/commands/SortCommand.java
src/main/java/seedu/address/logic/commands/ViewCommand.java
src/main/java/seedu/address/model/person/Name.java
src/test/java/seedu/address/logic/commands/SortCommandTest.java
src/test/java/seedu/address/model/person/PersonTest.java

- Changed the add command such that all names saved is in the format of first letter capital and the rest small
- i.e. bOb --> Bob, aLIcE --> Alice
- Changed persons to clients
Closes #243

Fix the name displayed

---

src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
src/test/java/seedu/address/logic/commands/reminder/AddReminderCommandTest.java

Update test for add reminder
Update equals method for add reminder command

Add AddReminderCommandTest

---

src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
src/main/java/seedu/address/logic/parser/reminder/AddReminderCommandParser.java
src/test/java/seedu/address/logic/parser/reminder/AddReminderCommandParserTest.java
src/test/java/seedu/address/logic/parser/reminder/DeleteReminderCommandParserTest.java
src/test/java/seedu/address/logic/parser/reminder/EditReminderCommandParserTest.java
src/test/java/seedu/address/logic/parser/reminder/EditReminderParserTest.java

Update add reminder command parser test

Update add reminder command parser test

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/ui/HelpWindow.java
src/main/resources/view/HelpWindow.fxml

* Updated help window with added short commands and new commands for reminder
* Standardised a client type in SampleDataUtil
* Checkstyle and typos
close #193

Branch bug fixes

---

docs/UserGuide.md

* Add the Command History feature into the additional feature section.
close #252

Add additional feature section into UserGuide

---

src/main/java/seedu/address/model/person/Name.java

- Edit the name error message
close #254

Fix name field message

---

src/test/java/seedu/address/logic/parser/reminder/AddReminderCommandParserTest.java
src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java

Update AddReminderCommandParserTest
Update NameContainsKeywordsPredicateTest

Branch update add reminder parser test

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/testutil/TypicalIndexes.java

* Add an additional check to see if the edited user have reminders,
* If no, allows the user to edit their name.
* If yes, do not allow users to edit their name.
close #262

Update edit command

---

src/main/java/seedu/address/logic/commands/reminder/EditReminderCommand.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/reminder/EditReminderCommandTest.java
src/test/java/seedu/address/logic/parser/reminder/EditReminderCommandParserTest.java

- Update LogicManagerTest
- Update EditReminderCommandTest
- Update EditReminderCommandParserTest

Branch add more test cases

---

src/main/java/seedu/address/logic/commands/reminder/EditReminderCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/reminder/ReminderComparator.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java

- Sort the reminder list according to earliest to latest
Closes #267

Sort reminder list

---

docs/UserGuide.md
src/main/java/seedu/address/logic/parser/ViewCommandParser.java
src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java

* User can now view according to the exact name of the client they input by indicating that it is a exact name with a / at the back.
* Reformat the UserGuide and update ViewCommand section.
close #265

Branch fix view

---

src/main/java/seedu/address/model/person/Address.java

- Added a filter to check if it works
Closes #270

Branch address constraint

---

src/main/java/seedu/address/model/reminder/ReminderDescription.java
src/main/java/seedu/address/ui/HelpWindow.java
src/main/resources/view/HelpWindow.css
src/main/resources/view/HelpWindow.fxml

Update help window and error message for ReminderDescription

---

src/main/resources/view/MainWindow.fxml

* Change the MinWidth from 400 to 1000.
* To not allow users to "squish" the UI.
close #281

Update MainWindow UI

---

docs/DeveloperGuide.md
src/main/java/seedu/address/logic/parser/ViewCommandParser.java

Add view in the use case
Modify the ViewCommandParser
Update the glossary

Update developer guide

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/FindAddressCommand.java
src/main/java/seedu/address/logic/commands/FindClientTypeCommand.java
src/main/java/seedu/address/logic/commands/FindNameCommand.java
src/main/java/seedu/address/logic/commands/FindPhoneCommand.java
src/main/java/seedu/address/logic/commands/ViewCommand.java
src/main/java/seedu/address/model/person/NameContainsKeywordsDeletePredicate.java
src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
src/test/java/seedu/address/logic/commands/FindAddressCommandTest.java
src/test/java/seedu/address/logic/commands/FindClientTypeCommandTest.java
src/test/java/seedu/address/logic/commands/FindNameCommandTest.java
src/test/java/seedu/address/logic/commands/FindPhoneCommandTest.java
src/test/java/seedu/address/logic/commands/ViewCommandTest.java

* Make the find name predicate more succinct
* Modify the algorithm for the different finds.

Update Name predicates

---

docs/DeveloperGuide.md
docs/UserGuide.md

Update quickstart of User guide
to be more beginner friendly

Update User Guide

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/model/reminder/Reminder.java

* Removed the "T" showing between the date and time for output messages of reminder commands.
close #296

Fix the date time format for reminder commands

---

src/main/java/seedu/address/logic/commands/reminder/EditReminderCommand.java
src/test/java/seedu/address/logic/commands/reminder/EditReminderCommandTest.java

- Display message shows the new reminder instead of old reminder
- You can edit different reminders
Closes #298

Fix edit reminder display message

---

docs/UserGuide.md

* Change the example instruction format under the FindClientType command

Update UG for findclienttype section

---

docs/_sass/minima/_base.scss

Update UserGuide header to
reflect the correct name

Update UserGuide header

---

docs/UserGuide.md
src/main/java/seedu/address/model/person/Name.java

Update Name.java to allow 1-letter name
Update typo in UG from 1234567 to 12345678 for add

Branch bug fixing

---

docs/UserGuide.md

* Fix weird formatting of the parameter specification table. 
* Add new stuff into the notes about the command format.

Fix parameter specification table

---

docs/DeveloperGuide.md
docs/UserGuide.md

- Update Edit and Add reminder in user guide mentioning the date time round off
- Add future enhancement to allow deleting all reminders
- Add future enhancement to improve phone number(dups detection and phone numbers from other countries)
- Add future enhancement to improve add and allow for more flexible fields
- Add future enhancement to improve find to allow stackable finds
- Added detail to target audience that clients they have are Singaporeans(restriction of Singaporean phone number)
- Add detail on delete

Update User and Developer Guide

---

src/main/java/seedu/address/logic/parser/ParserUtil.java

Fix Add Reminder bug where having
a description of longer than 300 characters
was failing silently
Close #333

Fix AddReminder Bug

---

src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/ViewPersonWindow.java

* Revert the "enhancement" changes from commit c4ec966

Revert the changes of the View Command fix

---

docs/UserGuide.md
src/main/java/seedu/address/ui/HelpWindow.java
src/main/resources/view/HelpWindow.fxml

* Add `$` in help window and UG for commands that require it
* Add missing [] to` redit` command in help window
* Formatting and delete repeated info in UG
* Add missing short commands to UG
close #308 
close #329 
close #318 
close #324 
close #348

Update help window and UG for consistency

---

docs/UserGuide.md

- Corrected one of the sentences

Correct one of the sentences
